<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    protected $fillable = ['title'];

//    public  function create() {
//        return null;
//    }
//    public function getRouteKeyName()
//    {
//        return 'title'; // TODO: Change the autogenerated stub
//    }
}
